using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using HealthcareSupport.CaseEvaluation.Branding;
using Shouldly;
using Xunit;

namespace HealthcareSupport.CaseEvaluation.AppointmentDocuments.Templates;

/// <summary>
/// A drift guard across the language boundary. The packet templates are generated by Python
/// (<c>tools/packet-templates/*/build_*.py</c>) and filled by .NET (<see cref="PacketTokenMap"/>),
/// and neither side references the other. A token a template uses that the map does not
/// supply renders LITERALLY -- the renderer leaves unknown tokens in place on purpose -- so a
/// typo in either file ships "##Office.PhysicanName##" onto a medical-legal notice with no
/// error anywhere. This reads the builder sources (the generated HTML is not tracked) and fails
/// on any token the map lacks.
/// </summary>
public class PacketTemplateTokenCoverageTests
{
    // The attorney builder's docstring names the token SHAPE, not a token.
    private static readonly HashSet<string> NotTokens = new() { "##Group.Field##" };

    [Fact]
    public void Every_token_a_packet_template_uses_is_supplied_by_the_token_map()
    {
        var mapKeys = PacketTokenMap.Build(new PacketTokenContext()).Keys.ToHashSet();
        var used = TemplateTokens();

        used.Count.ShouldBeGreaterThan(40, "the builders were found but yielded too few tokens to be real");
        used.Except(mapKeys).ShouldBeEmpty("tokens the templates use that PacketTokenMap does not supply");
    }

    [Fact]
    public void Every_office_token_in_the_map_is_used_by_some_template()
    {
        // The reverse direction, scoped to the office group this guard was written for: a mapped
        // office token no template prints means a field the office can edit that never reaches paper.
        var officeKeys = PacketTokenMap.Build(new PacketTokenContext()).Keys
            .Where(k => k.StartsWith("##Office.", System.StringComparison.Ordinal));

        officeKeys.Except(TemplateTokens()).ShouldBeEmpty();
    }

    [Fact]
    public void Office_tokens_carry_the_resolved_letterhead()
    {
        var map = PacketTokenMap.Build(new PacketTokenContext
        {
            Office = OfficeLetterhead.Compose(
                new OfficeLetterheadValues { Phone = "555-0100", MissedAppointmentFee = 10m },
                "TEST Office", "TEST-Ada", "TEST-Example"),
        });

        map["##Office.PhysicianName##"].ShouldBe("Dr. TEST-Ada TEST-Example");
        map["##Office.PracticeName##"].ShouldBe("TEST Office");
        map["##Office.Phone##"].ShouldBe("555-0100");
        map["##Office.PhoneFax##"].ShouldBe("Phone: 555-0100");
        map["##Office.Fax##"].ShouldBeEmpty();
        map["##Office.MissedAppointmentFee##"].ShouldBe("10.00");
    }

    private static HashSet<string> TemplateTokens()
    {
        var root = FindTemplatesRootOrThrow();
        return Directory.EnumerateFiles(root, "build_*.py", SearchOption.AllDirectories)
            .SelectMany(file => PacketTokenMap.TokenRegex.Matches(File.ReadAllText(file)).Select(m => m.Value))
            .Where(token => !NotTokens.Contains(token))
            .ToHashSet();
    }

    /// <summary>Walks up from this source file; throws rather than passing when the input is missing.</summary>
    private static string FindTemplatesRootOrThrow([CallerFilePath] string callerPath = "")
    {
        for (var directory = Directory.GetParent(callerPath); directory != null; directory = directory.Parent)
        {
            var candidate = Path.Combine(directory.FullName, "tools", "packet-templates");
            if (Directory.Exists(candidate))
            {
                return candidate;
            }
        }

        throw new ShouldAssertException(
            $"Could not find tools/packet-templates walking up from '{callerPath}'. " +
            "This test is a drift guard and must fail loudly when it cannot read its input.");
    }
}
