using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;

namespace HealthcareSupport.CaseEvaluation.AppointmentDefenseAttorneys;

public class EfCoreAppointmentDefenseAttorneysAppServiceTests : AppointmentDefenseAttorneysAppServiceTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
