using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;

namespace HealthcareSupport.CaseEvaluation.ApplicantAttorneys;

public class EfCoreApplicantAttorneysAppServiceTests : ApplicantAttorneysAppServiceTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
