using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;
using Xunit;

namespace HealthcareSupport.CaseEvaluation.ApplicantAttorneys;

[Collection(CaseEvaluationTestConsts.CollectionDefinitionName)]
public class EfCoreApplicantAttorneysAppServiceTests : ApplicantAttorneysAppServiceTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
