using HealthcareSupport.CaseEvaluation.DoctorAvailabilities;

namespace HealthcareSupport.CaseEvaluation.EntityFrameworkCore.Domains.DoctorAvailabilities;

public class EfCoreDoctorAvailabilityManagerTests : DoctorAvailabilityManagerTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
