using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;
using Xunit;

namespace HealthcareSupport.CaseEvaluation.DoctorAvailabilities;

[Collection(CaseEvaluationTestConsts.CollectionDefinitionName)]
public class EfCoreDoctorAvailabilitiesAppServiceTests : DoctorAvailabilitiesAppServiceTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
