using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;

namespace HealthcareSupport.CaseEvaluation.DoctorAvailabilities;

public class EfCoreDoctorAvailabilitiesAppServiceTests : DoctorAvailabilitiesAppServiceTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
