using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;

namespace HealthcareSupport.CaseEvaluation.AppointmentStatuses;

public class EfCoreAppointmentStatusesAppServiceTests : AppointmentStatusesAppServiceTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
