using HealthcareSupport.CaseEvaluation.ClaimExaminers;

namespace HealthcareSupport.CaseEvaluation.EntityFrameworkCore.Domains.ClaimExaminers;

public class EfCoreClaimExaminerManagerTests : ClaimExaminerManagerTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
