using System.Reflection;

namespace HealthcareSupport.CaseEvaluation.AppointmentDocuments.Templates;

/// <summary>
/// Loads OLD-verbatim packet DOCX templates from embedded resources under
/// <c>AppointmentDocuments\Templates\Resources\</c>. The 3 active OLD
/// templates are copied byte-identical from
/// <c>P:\PatientPortalOld\PatientAppointment.Api\wwwroot\Documents\documentBluePrint\</c>:
///
/// <list type="bullet">
///   <item><description>PatientPacketNew.docx (343 KB) -- patient packet emailed + saved</description></item>
///   <item><description>DoctorPacket.docx (1.0 MB) -- doctor packet, saved only (not emailed)</description></item>
///   <item><description>AttorneyClaimExaminerPacket.docx (49 KB) -- shipped to every active claim examiner, defense attorney, patient attorney on PQME/AME appointments</description></item>
/// </list>
///
/// <para>Resource names are auto-generated by the compiler from the
/// project's <c>RootNamespace</c> + folder path, so a file at
/// <c>AppointmentDocuments\Templates\Resources\PatientPacketNew.docx</c>
/// becomes
/// <c>HealthcareSupport.CaseEvaluation.AppointmentDocuments.Templates.Resources.PatientPacketNew.docx</c>.
/// The kind-keyed <see cref="LoadTemplate"/> helper hides that wiring.</para>
///
/// <para>Returns a fresh byte[] per call; callers may mutate freely
/// (e.g. token-replace + signature-stamp before write).</para>
/// </summary>
public static class EmbeddedTemplateResources
{
    private const string ResourceFolder =
        "HealthcareSupport.CaseEvaluation.AppointmentDocuments.Templates.Resources";

    private static readonly Assembly OwningAssembly = typeof(EmbeddedTemplateResources).Assembly;

    /// <summary>
    /// Returns the embedded DOCX bytes for the given <paramref name="kind"/>.
    /// Throws when the resource is missing -- a missing template at runtime
    /// is a build-error-class problem (the .csproj glob should include it).
    /// </summary>
    public static byte[] LoadTemplate(PacketKind kind)
    {
        var fileName = ResourceFileName(kind);
        var resourceName = $"{ResourceFolder}.{fileName}";

        using var stream = OwningAssembly.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException(
                $"Packet template resource not found for kind '{kind}'. " +
                $"Expected an embedded DOCX at '{resourceName}'.");

        using var memory = new MemoryStream();
        stream.CopyTo(memory);
        return memory.ToArray();
    }

    /// <summary>
    /// Maps a PacketKind to the embedded resource filename. The mapping is
    /// stable; renaming a resource file requires an explicit update here.
    /// </summary>
    public static string ResourceFileName(PacketKind kind) => kind switch
    {
        PacketKind.Patient => "PatientPacketNew.docx",
        PacketKind.Doctor => "DoctorPacket.docx",
        PacketKind.AttorneyClaimExaminer => "AttorneyClaimExaminerPacket.docx",
        _ => throw new ArgumentOutOfRangeException(nameof(kind), kind, "No embedded template registered for this PacketKind."),
    };
}
