using Asp.Versioning;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using HealthcareSupport.CaseEvaluation.AppointmentDocuments;
using Microsoft.AspNetCore.Mvc;
using Volo.Abp;
using Volo.Abp.AspNetCore.Mvc;

namespace HealthcareSupport.CaseEvaluation.Controllers.AppointmentDocuments;

/// <summary>
/// W2-11: per-appointment merged-PDF packet endpoints. The packet is
/// generated by the Hangfire job triggered on appointment approval; this
/// controller reads packet status + streams the final PDF for download.
/// Regenerate is exposed on <see cref="AppointmentDocumentController"/>
/// at /api/app/appointments/{appointmentId}/packet/regenerate.
/// </summary>
[RemoteService]
[Area("app")]
[ControllerName("AppointmentPacket")]
[Route("api/app/appointments/{appointmentId}/packet")]
public class AppointmentPacketController : AbpController
{
    private readonly IAppointmentPacketsAppService _service;

    public AppointmentPacketController(IAppointmentPacketsAppService service)
    {
        _service = service;
    }

    [HttpGet]
    public virtual Task<AppointmentPacketDto?> GetByAppointmentAsync(Guid appointmentId)
    {
        return _service.GetByAppointmentAsync(appointmentId);
    }

    [HttpGet("download")]
    public virtual async Task<IActionResult> DownloadAsync(Guid appointmentId)
    {
        var result = await _service.DownloadAsync(appointmentId);
        return File(result.Content, result.ContentType, result.FileName);
    }

    [HttpGet("list")]
    public virtual Task<List<AppointmentPacketDto>> GetListByAppointmentAsync(Guid appointmentId)
    {
        return _service.GetListByAppointmentAsync(appointmentId);
    }

    [HttpGet("download/{kind}")]
    public virtual async Task<IActionResult> DownloadByKindAsync(Guid appointmentId, PacketKind kind)
    {
        var result = await _service.DownloadByKindAsync(appointmentId, kind);
        return File(result.Content, result.ContentType, result.FileName);
    }
}
