using HealthcareSupport.CaseEvaluation.AppointmentPrimaryInsurances;

namespace HealthcareSupport.CaseEvaluation.EntityFrameworkCore.Domains.AppointmentPrimaryInsurances;

public class EfCoreAppointmentPrimaryInsuranceManagerTests : AppointmentPrimaryInsuranceManagerTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
