
namespace HealthcareSupport.CaseEvaluation.EntityFrameworkCore.Applications;

public class EfCoreErrorCodeLocalizationTests : ErrorCodeLocalizationTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
