using System;
using System.IO;
using System.Reflection;

namespace HealthcareSupport.CaseEvaluation.NotificationTemplates;

/// <summary>
/// Loads OLD-verbatim email-template HTML bodies from embedded resources
/// under <c>NotificationTemplates\EmailBodies\*.html</c>. The files mirror
/// OLD's <c>P:\PatientPortalOld\PatientAppointment.Api\wwwroot\EmailTemplates\</c>
/// catalog one-for-one so per-template diffs against OLD are clean.
///
/// <para>Resource names are auto-generated by the C# compiler from the
/// project's <c>RootNamespace</c> + folder path, so a file at
/// <c>NotificationTemplates\EmailBodies\UserRegistered.html</c> in this
/// project becomes
/// <c>HealthcareSupport.CaseEvaluation.NotificationTemplates.EmailBodies.UserRegistered.html</c>.
/// The <see cref="LoadBody"/> helper hides that wiring; callers pass the
/// short filename without extension (matches the
/// <see cref="NotificationTemplateConsts.Codes"/> code constants).</para>
///
/// <para>If a code does not have a corresponding embedded resource (the
/// majority of the 59 codes are still on stub bodies), <see cref="TryLoadBody"/>
/// returns <c>false</c> so the seed contributor can fall back to the stub.
/// This is the demo-critical-only adoption pattern; per-feature phases
/// add more <c>.html</c> files over time.</para>
/// </summary>
internal static class EmailBodyResources
{
    private const string ResourceFolder =
        "HealthcareSupport.CaseEvaluation.NotificationTemplates.EmailBodies";

    private static readonly Assembly OwningAssembly = typeof(EmailBodyResources).Assembly;

    /// <summary>
    /// Loads the embedded body for <paramref name="templateCode"/>. Returns
    /// <c>null</c> when no resource exists. Callers compose the fallback
    /// (typically a stub string) when the resource is absent.
    /// </summary>
    public static string? TryLoadBody(string templateCode)
    {
        if (string.IsNullOrWhiteSpace(templateCode))
        {
            return null;
        }

        var resourceName = $"{ResourceFolder}.{templateCode}.html";
        using var stream = OwningAssembly.GetManifestResourceStream(resourceName);
        if (stream == null)
        {
            return null;
        }

        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    /// <summary>
    /// Loads the embedded body for <paramref name="templateCode"/>; throws
    /// when the resource is missing. Use only at startup when a missing
    /// resource is a build-error-class problem (e.g. the file was deleted
    /// without updating the dispatch map).
    /// </summary>
    public static string LoadBody(string templateCode)
    {
        return TryLoadBody(templateCode)
            ?? throw new InvalidOperationException(
                $"Email body resource not found for template code '{templateCode}'. " +
                $"Expected an embedded HTML file at '{ResourceFolder}.{templateCode}.html'.");
    }
}
