using HealthcareSupport.CaseEvaluation.AppointmentBodyParts;
using Xunit;

namespace HealthcareSupport.CaseEvaluation.EntityFrameworkCore.Domains.AppointmentBodyParts;

[Collection(CaseEvaluationTestConsts.CollectionDefinitionName)]
public class EfCoreAppointmentBodyPartManagerTests : AppointmentBodyPartManagerTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
