using HealthcareSupport.CaseEvaluation.Appointments;

namespace HealthcareSupport.CaseEvaluation.EntityFrameworkCore.Applications.Appointments;

public class EfCoreAttorneyUpsertBranchTests : AttorneyUpsertBranchTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
