using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;

namespace HealthcareSupport.CaseEvaluation.Appointments;

public class EfCoreAppointmentChildDeleteOwnershipTests : AppointmentChildDeleteOwnershipTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
