using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;

namespace HealthcareSupport.CaseEvaluation.Appointments;

public class EfCoreAppointmentsAppServiceSuppliedPatientIdTests
    : AppointmentsAppServiceSuppliedPatientIdTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
