using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;

namespace HealthcareSupport.CaseEvaluation.Appointments;

public class EfCoreAppointmentReadAccessGuardTests : AppointmentReadAccessGuardTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
