using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;

namespace HealthcareSupport.CaseEvaluation.Appointments;

public class EfCoreAppointmentChildReadOwnershipTests : AppointmentChildReadOwnershipTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
