using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;

namespace HealthcareSupport.CaseEvaluation.Appointments;

public class EfCoreAppointmentsAppServiceTests : AppointmentsAppServiceTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
