using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;

namespace HealthcareSupport.CaseEvaluation.ClaimExaminers;

public class EfCoreClaimExaminersAppServiceTests : ClaimExaminersAppServiceTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
