namespace HealthcareSupport.CaseEvaluation.AppointmentDocuments;

/// <summary>
/// Unified read shape for the patient's "my documents" view -- one row
/// per visible artifact regardless of whether it was uploaded by the
/// patient, generated by the portal, or supplied by the office.
///
/// <para>Phase 1D.10 closes the OLD-parity gap where the Patient Packet
/// was persisted to OLD's <c>AppointmentNewDocument</c> table and
/// surfaced in the patient's documents list alongside their uploads.
/// NEW keeps the two storage shapes physically separate but unions
/// them at read time.</para>
/// </summary>
public class PatientPortalDocumentDto
{
    /// <summary>The underlying row's Id (AppointmentDocument.Id or AppointmentPacket.Id).</summary>
    public Guid Id { get; set; }

    /// <summary>Discriminator -- which table the row came from.</summary>
    public PatientPortalDocumentSource Source { get; set; }

    /// <summary>Display filename. For Uploaded rows: the original file name.
    /// For GeneratedPacket rows: the OLD-style {Confirmation}_{KindName}_{ddMMyyyy_hhmmss}.docx.</summary>
    public string FileName { get; set; } = string.Empty;

    /// <summary>MIME type. <c>application/vnd.openxmlformats-officedocument.wordprocessingml.document</c>
    /// for Phase 1 packets; original upload type for Uploaded rows.</summary>
    public string ContentType { get; set; } = string.Empty;

    /// <summary>UTC creation time -- used as the default sort key.</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>Generated-packet rows: the kind. Null for Uploaded rows.</summary>
    public PacketKind? PacketKind { get; set; }

    /// <summary>Uploaded rows: the review status (Accepted / Pending / Rejected).
    /// Null for GeneratedPacket rows (always implicitly Accepted).</summary>
    public DocumentStatus? UploadStatus { get; set; }
}

public enum PatientPortalDocumentSource
{
    Uploaded = 1,
    GeneratedPacket = 2,
}
