#!/usr/bin/env bash
# add-worktree.sh <branch>
#
# Creates a feature worktree under /w/patient-portal/ with auto-allocated ports
# (+10 per existing non-persistent worktree beyond main+dev+staging), copies
# secrets, renders appsettings.Local.json + environment.local.ts, runs restore
# + yarn install, and appends per-worktree compose overrides to the new .env.
#
# Feature worktrees share main's CaseEvaluation SQL container's default DB
# name, but run in their own compose project (own SQL container, own volume).
# Run DbMigrator from inside the new worktree to seed its DB if needed; a
# feature worktree started via `docker compose up -d` will trigger db-migrator
# automatically as part of the compose dependency graph.
#
# Usage: ./add-worktree.sh feat/287-contact-method
set -euo pipefail

BRANCH="${1:?usage: add-worktree.sh <branch-name>}"
SLUG="$(echo "$BRANCH" | tr '/' '-')"
ROOT="/w/patient-portal"
MAIN="$ROOT/main"
TARGET="$ROOT/$SLUG"

[ -d "$TARGET" ] && { echo "error: $TARGET already exists" >&2; exit 1; }

# Main must have a populated .env before we can seed the new worktree's .env.
# .env is gitignored so `git worktree add` does not carry it forward; we copy
# main's file below. Fail fast with a clear bootstrap hint if main is not set
# up yet.
if [ ! -f "$MAIN/.env" ]; then
  echo "error: $MAIN/.env not found." >&2
  echo "  bootstrap with: cp $MAIN/.env.example $MAIN/.env && edit to fill in secrets" >&2
  exit 1
fi

# Pick the next +10 port offset. main/development/staging hold offsets 0/1/2;
# feature worktrees take offset 3 onward.
offset=3
cd "$MAIN"
while IFS= read -r wt; do
  name="$(basename "$wt")"
  case "$name" in
    main|development|staging) ;;
    *) offset=$((offset + 1)) ;;
  esac
done < <(git worktree list --porcelain | awk '/^worktree/ {print $2}')

AUTH=$((44368 + offset * 10))
API=$((44327 + offset * 10))
NG=$((4200 + offset * 10))
SQL_HOST=$((1434 + offset))
REDIS_HOST=$((6379 + offset))
DB="CaseEvaluation"

echo "Creating $SLUG at $TARGET (AUTH=$AUTH API=$API NG=$NG SQL=$SQL_HOST REDIS=$REDIS_HOST)"

cd "$MAIN"
git fetch origin
if git show-ref --verify --quiet "refs/heads/$BRANCH" \
   || git show-ref --verify --quiet "refs/remotes/origin/$BRANCH"; then
  git worktree add "$TARGET" "$BRANCH"
else
  git worktree add -b "$BRANCH" "$TARGET" main
fi

# Seed .env (and .env.local if present) from main. `git worktree add` only
# checks out tracked files, so the new worktree has neither file until we
# copy. Copy rather than symlink so per-worktree secrets can drift if ever
# needed (e.g. scoped test credentials); by default they match main.
cp "$MAIN/.env" "$TARGET/.env"
[ -f "$MAIN/.env.local" ] && cp "$MAIN/.env.local" "$TARGET/.env.local"

# Copy secrets into all worktrees (this includes the new one).
"$MAIN/scripts/worktrees/refresh-secrets.sh"

# Render per-worktree dotnet + Angular source-level config (for direct
# dotnet-run fallback; compose uses env vars instead).
"$MAIN/scripts/worktrees/render-config.sh" "$TARGET" "$AUTH" "$API" "$NG" "$DB"

# Append compose overrides to the new worktree's .env so `docker compose up -d`
# isolates host ports and uses the right Angular build configuration.
cat >> "$TARGET/.env" <<ENV

# --- Per-worktree compose overrides (auto-generated by add-worktree.sh) ---
AUTH_PORT=$AUTH
API_PORT=$API
NG_PORT=$NG
SQL_HOST_PORT=$SQL_HOST
REDIS_HOST_PORT=$REDIS_HOST
NG_CONFIG=local
ENV

# Install deps for direct dotnet-run paths (optional for compose users).
cd "$TARGET"
dotnet restore
(cd angular && yarn install --mutex network)

cat <<NOTE

Worktree $SLUG ready at $TARGET.
  AuthServer:   http://localhost:$AUTH
  HttpApi.Host: http://localhost:$API
  Angular:      http://localhost:$NG
  SQL:          localhost:$SQL_HOST
  Redis:        localhost:$REDIS_HOST

To start the stack:
  cd $TARGET && docker compose up -d

See docs/runbooks/DOCKER-DEV.md for operations.
NOTE
