using HealthcareSupport.CaseEvaluation.Uploads;

namespace HealthcareSupport.CaseEvaluation.EntityFrameworkCore.Domains.Uploads;

public class EfCoreUploadContainerScanWiringTests : UploadContainerScanWiringTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
