using HealthcareSupport.CaseEvaluation.AppointmentClaimExaminers;

namespace HealthcareSupport.CaseEvaluation.EntityFrameworkCore.Domains.AppointmentClaimExaminers;

public class EfCoreAppointmentClaimExaminerManagerTests : AppointmentClaimExaminerManagerTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
