using HealthcareSupport.CaseEvaluation.Appointments;
using System;
using JetBrains.Annotations;
using Volo.Abp;
using Volo.Abp.Auditing;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;

namespace HealthcareSupport.CaseEvaluation.AppointmentDocuments;

/// <summary>
/// Per-(appointment, kind) generated packet. After the OLD-parity rework
/// (Phase 1A.1) the table holds one row per (TenantId, AppointmentId,
/// Kind) tuple, so a single appointment can have up to 3 distinct rows:
/// Patient, Doctor, and AttorneyClaimExaminer. Composite uniqueness is
/// enforced in the EF model.
///
/// The AttorneyClaimExaminer row holds a single rendered DOCX that the
/// email session attaches to every atty/CE recipient (claim examiners,
/// defense attorneys, patient attorneys) -- not persisted per recipient.
///
/// Generated by <see cref="Jobs.GenerateAppointmentPacketJob"/> when the
/// appointment transitions to Approved. Regenerated when the office calls
/// <c>RegeneratePacketAsync</c>.
///
/// Phase 1 ships DOCX bytes per kind. Phase 2 layers DOCX -> PDF
/// conversion on top. Blob path:
///   {tenantSegment}/{appointmentId}/packet/{kindSegment}/{packetGuid}.{ext}
/// </summary>
[Audited]
public class AppointmentPacket : FullAuditedAggregateRoot<Guid>, IMultiTenant
{
    public virtual Guid? TenantId { get; set; }

    /// <summary>FK to the appointment this packet represents.</summary>
    public virtual Guid AppointmentId { get; set; }

    /// <summary>
    /// Per-recipient packet kind. Combined with AppointmentId via a
    /// composite unique index so a single appointment can persist up to
    /// 6 rows (one per kind).
    /// </summary>
    public virtual PacketKind Kind { get; set; }

    /// <summary>Blob storage key (tenant-prefixed GUID path).</summary>
    [NotNull]
    public virtual string BlobName { get; set; } = null!;

    /// <summary>Generating / Generated / Failed.</summary>
    public virtual PacketGenerationStatus Status { get; set; }

    /// <summary>UTC timestamp when packet first reached Generated.</summary>
    public virtual DateTime GeneratedAt { get; set; }

    /// <summary>UTC timestamp when packet was last regenerated; null if never regenerated.</summary>
    public virtual DateTime? RegeneratedAt { get; set; }

    /// <summary>If Status = Failed, captures the exception message for UI display.</summary>
    [CanBeNull]
    public virtual string? ErrorMessage { get; set; }

    protected AppointmentPacket()
    {
    }

    public AppointmentPacket(
        Guid id,
        Guid? tenantId,
        Guid appointmentId,
        PacketKind kind,
        string blobName,
        PacketGenerationStatus status = PacketGenerationStatus.Generating)
    {
        Id = id;
        TenantId = tenantId;
        AppointmentId = appointmentId;
        Kind = kind;
        BlobName = blobName;
        Status = status;
        GeneratedAt = DateTime.UtcNow;

        Check.NotNullOrWhiteSpace(BlobName, nameof(blobName));
        Check.Length(BlobName, nameof(blobName), AppointmentPacketConsts.BlobNameMaxLength);
    }
}
