using HealthcareSupport.CaseEvaluation.Appointments;
using System;
using JetBrains.Annotations;
using Volo.Abp;
using Volo.Abp.Auditing;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;

namespace HealthcareSupport.CaseEvaluation.AppointmentDocuments;

/// <summary>
/// W2-11: per-appointment merged-PDF packet. One row per Appointment.
/// Generated by <see cref="Jobs.GenerateAppointmentPacketJob"/> when the
/// appointment transitions to Approved. Regenerated when the office calls
/// <c>RegeneratePacketAsync</c> after approving additional documents.
///
/// Format adopted from OLD (which produced DOCX per recipient via
/// DocumentFormat.OpenXml mail-merge of pre-authored templates) but
/// rendered as a single PDF per appointment for MVP -- per Adrian's
/// directive "ensure we make a pdf until I get the confirmed format".
/// Per-recipient templates + token mail-merge are a deferred enhancement
/// when the manager confirms the exact format.
///
/// Blob path follows the same tenant-prefixed convention as
/// <see cref="AppointmentDocument"/>:
///   {tenantSegment}/{appointmentId}/packet/{packetGuid}.pdf
/// </summary>
[Audited]
public class AppointmentPacket : FullAuditedAggregateRoot<Guid>, IMultiTenant
{
    public virtual Guid? TenantId { get; set; }

    /// <summary>FK to the appointment this packet represents (1:1 logically).</summary>
    public virtual Guid AppointmentId { get; set; }

    /// <summary>Blob storage key (tenant-prefixed GUID path).</summary>
    [NotNull]
    public virtual string BlobName { get; set; } = null!;

    /// <summary>Generating / Generated / Failed.</summary>
    public virtual PacketGenerationStatus Status { get; set; }

    /// <summary>UTC timestamp when packet first reached Generated.</summary>
    public virtual DateTime GeneratedAt { get; set; }

    /// <summary>UTC timestamp when packet was last regenerated; null if never regenerated.</summary>
    public virtual DateTime? RegeneratedAt { get; set; }

    /// <summary>If Status = Failed, captures the exception message for UI display.</summary>
    [CanBeNull]
    public virtual string? ErrorMessage { get; set; }

    protected AppointmentPacket()
    {
    }

    public AppointmentPacket(
        Guid id,
        Guid? tenantId,
        Guid appointmentId,
        string blobName,
        PacketGenerationStatus status = PacketGenerationStatus.Generating)
    {
        Id = id;
        TenantId = tenantId;
        AppointmentId = appointmentId;
        BlobName = blobName;
        Status = status;
        GeneratedAt = DateTime.UtcNow;

        Check.NotNullOrWhiteSpace(BlobName, nameof(blobName));
        Check.Length(BlobName, nameof(blobName), AppointmentPacketConsts.BlobNameMaxLength);
    }
}
