using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;

namespace HealthcareSupport.CaseEvaluation.WcabOffices;

public class EfCoreWcabOfficesAppServiceTests : WcabOfficesAppServiceTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
