using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;

namespace HealthcareSupport.CaseEvaluation.AppointmentPrimaryInsurances;

public class EfCoreAppointmentPrimaryInsurancesAppServiceTests : AppointmentPrimaryInsurancesAppServiceTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
