using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;

namespace HealthcareSupport.CaseEvaluation.AppointmentApplicantAttorneys;

public class EfCoreAppointmentApplicantAttorneysAppServiceTests : AppointmentApplicantAttorneysAppServiceTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
