using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;
using Xunit;

namespace HealthcareSupport.CaseEvaluation.AppointmentApplicantAttorneys;

[Collection(CaseEvaluationTestConsts.CollectionDefinitionName)]
public class EfCoreAppointmentApplicantAttorneysAppServiceTests : AppointmentApplicantAttorneysAppServiceTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
