using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;

namespace HealthcareSupport.CaseEvaluation.AppointmentTypes;

public class EfCoreAppointmentTypesAppServiceTests : AppointmentTypesAppServiceTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
