using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;

namespace HealthcareSupport.CaseEvaluation.AppointmentAccessors;

public class EfCoreAppointmentAccessorsAppServiceTests : AppointmentAccessorsAppServiceTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
