using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;

namespace HealthcareSupport.CaseEvaluation.AppointmentClaimExaminers;

public class EfCoreAppointmentClaimExaminersAppServiceTests : AppointmentClaimExaminersAppServiceTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
