using HealthcareSupport.CaseEvaluation.EntityFrameworkCore;

namespace HealthcareSupport.CaseEvaluation.AppointmentEmployerDetails;

public class EfCoreAppointmentEmployerDetailsAppServiceTests : AppointmentEmployerDetailsAppServiceTests<CaseEvaluationEntityFrameworkCoreTestModule>
{
}
